[package]
name = "raxolotl"
version = "0.1.0"
authors = ["kar"]
edition = "2018"

[lib]
name = "raxolotl"
crate-type = ["rlib"]
# crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
num = "^0.3.0"
